---
language: bash

addons:
  apt:
    sources:
      - debian-sid
    packages:
      - shellcheck

before_install:
  - nvm install stable
  - nvm use stable

install:
  - npm install -g textlint textlint-plugin-markdown textlint-rule-no-todo
    textlint-rule-no-empty-section textlint-rule-common-misspellings
    textlint-rule-alex textlint-rule-rousseau

script:
  - find . -name '*.md' -print0 | xargs -n1 -0 textlint -f pretty-error --rule no-todo,no-empty-section,common-misspellings,alex
  - find . -name '*.sh' -print0 | xargs -n1 -0 shellcheck -s bash
